force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>CART-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>ShopSphere_Customer__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Total_Amount__c.field-meta.xml
<CustomField>

    
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <type>Summary</type>
        <summaryForeignKey>Cart_Item__c.Cart__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <summarizedField>Cart_Item__c.Total_Price__c</summarizedField>
    
</CustomField>

force-app/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/fields/Cart__c.field-meta.xml
<CustomField>

    
        <fullName>Cart__c</fullName>
        <label>Cart</label>
        <type>MasterDetail</type>
        <referenceTo>Cart__c</referenceTo>
        <relationshipName>Cart_Items</relationshipName>
    
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Price__c.field-meta.xml
<CustomField>

    
        <fullName>Price__c</fullName>
        <label>Price</label>
        <type>Currency</type>
        <scale>2</scale>
        <precision>18</precision>
    
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Product__c.field-meta.xml
<CustomField>

    
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Lookup</type>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Cart_Items</relationshipName>
    
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>

    
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <type>Number</type>
        <scale>0</scale>
        <precision>18</precision>
        <defaultValue>1</defaultValue>
    
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Total_Price__c.field-meta.xml
<CustomField>

    
        <fullName>Total_Price__c</fullName>
        <label>Total Price</label>
        <type>Currency</type>
        <precision>18</precision>
        <scale>2</scale>
        <formula>Quantity__c * Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product__c/fields/Image_URL__c.field-meta.xml
<CustomField>

    
        <fullName>Image_URL__c</fullName>
        <label>Image URL</label>
        <type>Url</type>
    
</CustomField>

force-app/main/default/classes/CartSelector.cls
public inherited sharing class CartSelector {
    public Cart__c getActiveCartByCustomerId(Id customerId) {
        List<Cart__c> carts = [SELECT Id, Total_Amount__c, 
                               (SELECT Id, Product__c, Product__r.Name, Product__r.Image_URL__c, Quantity__c, Price__c, Total_Price__c FROM Cart_Items__r) 
                               FROM Cart__c WHERE Customer__c = :customerId LIMIT 1];
        return carts.isEmpty() ? null : carts[0];
    }
    
    public List<Cart_Item__c> getCartItem(Id cartId, Id productId) {
        return [SELECT Id, Quantity__c FROM Cart_Item__c WHERE Cart__c = :cartId AND Product__c = :productId];
    }
}