force-app/main/default/objects/Cart__c/Cart__c.object-meta.xml
<CustomObject>
    <label>Cart</label>
    <nameField>
        <displayFormat>CART-{0000}</displayFormat>
        <label>Cart Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Carts</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>ShopSphere_Customer__c</referenceTo>
    <relationshipLabel>Carts</relationshipLabel>
    <relationshipName>Carts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cart__c/fields/Total_Amount__c.field-meta.xml
<CustomField>

    
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <type>Summary</type>
        <summaryForeignKey>Cart_Item__c.Cart__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <summarizedField>Cart_Item__c.Total_Price__c</summarizedField>
    
</CustomField>

force-app/main/default/objects/Cart_Item__c/Cart_Item__c.object-meta.xml
<CustomObject>
    <label>Cart Item</label>
    <nameField>
        <displayFormat>CI-{00000}</displayFormat>
        <label>Cart Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cart_Item__c/fields/Cart__c.field-meta.xml
<CustomField>

    
        <fullName>Cart__c</fullName>
        <label>Cart</label>
        <type>MasterDetail</type>
        <referenceTo>Cart__c</referenceTo>
        <relationshipName>Cart_Items</relationshipName>
    
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Price__c.field-meta.xml
<CustomField>

    
        <fullName>Price__c</fullName>
        <label>Price</label>
        <type>Currency</type>
        <scale>2</scale>
        <precision>18</precision>
    
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Product__c.field-meta.xml
<CustomField>

    
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Lookup</type>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Cart_Items</relationshipName>
    
</CustomField>

force-app/main/default/objects/Cart_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>

    
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <type>Number</type>
        <scale>0</scale>
        <precision>18</precision>
        <defaultValue>1</defaultValue>
    
</CustomField>

force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>ORD-{000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Order__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>ShopSphere_Customer__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order__c/fields/Delivery_Address__c.field-meta.xml
<CustomField>

    
        <fullName>Delivery_Address__c</fullName>
        <label>Delivery Address</label>
        <type>TextArea</type>
    
</CustomField>

force-app/main/default/objects/Order__c/fields/Payment_Method__c.field-meta.xml
<CustomField>

    
        <fullName>Payment_Method__c</fullName>
        <label>Payment Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>PayPal</fullName>
                </value>
                <value>
                    <fullName>Cash on Delivery</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    
</CustomField>

force-app/main/default/objects/Order__c/fields/Status__c.field-meta.xml
<CustomField>

    
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Processing</fullName>
                </value>
                <value>
                    <fullName>Shipped</fullName>
                </value>
                <value>
                    <fullName>Delivered</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    
</CustomField>

force-app/main/default/objects/Order__c/fields/Total_Amount__c.field-meta.xml
<CustomField>

    
        <fullName>Total_Amount__c</fullName>
        <label>Total Amount</label>
        <type>Currency</type>
        <scale>2</scale>
        <precision>18</precision>
    
</CustomField>

force-app/main/default/objects/Order_Item__c/Order_Item__c.object-meta.xml
<CustomObject>
    <label>Order Item</label>
    <nameField>
        <displayFormat>OI-{000000}</displayFormat>
        <label>Order Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>

    
        <fullName>Order__c</fullName>
        <label>Order</label>
        <type>MasterDetail</type>
        <referenceTo>Order__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
    
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>

    
        <fullName>Product__c</fullName>
        <label>Product</label>
        <type>Lookup</type>
        <referenceTo>Product__c</referenceTo>
        <relationshipName>Order_Items</relationshipName>
    
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Quantity__c.field-meta.xml
<CustomField>

    
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <type>Number</type>
        <scale>0</scale>
        <precision>18</precision>
    
</CustomField>

force-app/main/default/objects/Product__c/Product__c.object-meta.xml
<CustomObject>
    <label>Product</label>
    <nameField>
        
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CartService.cls
public inherited sharing class CartService {
    private CartSelector cartSelector = new CartSelector();
    
    public Cart__c getOrCreateActiveCart(Id customerId) {
        Cart__c cart = cartSelector.getActiveCartByCustomerId(customerId);
        if (cart == null) {
            cart = new Cart__c(Customer__c = customerId);
            insert cart;
            cart = cartSelector.getActiveCartByCustomerId(customerId);
        }
        return cart;
    }
    
    public void addItemToCart(Id customerId, Id productId, Integer quantity) {
        Cart__c cart = getOrCreateActiveCart(customerId);
        Product__c prod = new ProductSelector().getProductById(productId);
        if(prod == null) throw new ShopSphereException('Product not found');
        
        List<Cart_Item__c> existingItems = cartSelector.getCartItem(cart.Id, productId);
        if (!existingItems.isEmpty()) {
            existingItems[0].Quantity__c += quantity;
            update existingItems[0];
        } else {
            insert new Cart_Item__c(Cart__c = cart.Id, Product__c = productId, Quantity__c = quantity, Price__c = prod.Price__c);
        }
    }
    
    public void updateItemQuantity(Id cartItemId, Integer quantity) {
        if(quantity <= 0) {
            delete [SELECT Id FROM Cart_Item__c WHERE Id = :cartItemId];
        } else {
            update new Cart_Item__c(Id = cartItemId, Quantity__c = quantity);
        }
    }
    
    public String checkoutCart(Id customerId, String deliveryAddress, String paymentMethod) {
        Cart__c cart = getOrCreateActiveCart(customerId);
        if (cart.Cart_Items__r.isEmpty()) throw new ShopSphereException('Cart is empty');
        
        Savepoint sp = Database.setSavepoint();
        try {
            Order__c newOrder = new Order__c(
                Customer__c = customerId, Total_Amount__c = cart.Total_Amount__c, Status__c = 'Pending',
                Delivery_Address__c = deliveryAddress, Payment_Method__c = paymentMethod
            );
            insert newOrder;
            
            List<Order_Item__c> orderItems = new List<Order_Item__c>();
            for(Cart_Item__c ci : cart.Cart_Items__r) {
                orderItems.add(new Order_Item__c(Order__c = newOrder.Id, Product__c = ci.Product__c, Quantity__c = ci.Quantity__c, Price__c = ci.Price__c));
            }
            insert orderItems;
            delete cart; 
            return newOrder.Id;
        } catch(Exception e) {
            Database.rollback(sp);
            throw new ShopSphereException('Checkout failed: ' + e.getMessage());
        }
    }
}